name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build for GH Pages
        run: hugo --minify

      - name: Deploy on GH Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Build for Rede Linux
        run: hugo --minify --environment redelinux

      - name: Deploy on Rede Linux
        if: github.ref == 'refs/heads/main'
        env:
          REDELINUX_PASS: ${{ secrets.REDELINUX_PASS }}
          REDELINUX_USER: ${{ secrets.REDELINUX_USER }}
          REDELINUX_HOST: ${{ secrets.REDELINUX_HOST }}
          REDELINUX_PATH: ${{ secrets.REDELINUX_PATH }}
        run: |
          sshpass -p "$REDELINUX_PASS" rsync --progress -avz -e "ssh -o StrictHostKeyChecking=no" public/* "$REDELINUX_USER@$REDELINUX_HOST:$REDELINUX_PATH"
